name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install SSH key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_NAME }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd 2024BetaAnalysis
          docker-compose down
          git pull origin main
          docker-compose up -d
