name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Debug Secrets
      run: |
        echo ${{ secrets.EC2_HOST_NAME }}
        echo ${{ secrets.EC2_SSH_KEY }}
        echo ${{ vars.IP }}
        echo ${{ vars.SSH }}
    

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST_NAME }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd 2024BetaAnalysis
          docker-compose down
          git pull origin main
          docker-compose up -d
