name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write SSH Key to file
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key
        chmod 600 private_key

    - name: Debug SSH Key
      run: |
          echo "Checking SHA256 hash of private_key:"
          sha256sum private_key

    - name: Check Private Key File Siz
      run: |
        echo "File size of private_key:"
        stat --format="%s" private_key

  
    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_NAME }}
        username: ubuntu
        key_path: ./private_key
        script: |
          cd 2024BetaAnalysis
          docker-compose down
          git pull origin main
          docker-compose up -d

    - name: Clean up private key
      run: rm private_key
